### ISSUE TITLE
how to add Pinch and Rotation gesture?

### ISSUE THREAD

**Issue by Mitesh-Mewada** [rubygarage/arkit-example#1]
Hello i am working one AR Project i check your example its great, i want to add **Pinch** and **Rotation** gesture on added AR object. **How can i do?** any idea.

**Comment by AntonoffEvgeniy** [comment]
Hello Mitesh-Mewada! 
You can add **Pinch** and **Rotation** gestures from UI objects library in Interface Builder. After that you can use **rotateBy** method of **SCNAction** for rotation and **scale** for resizing
See the documentation [https://developer.apple.com/documentation/scenekit/scnaction](url)
